version: '3.8'
services:
  db:
    container_name: nestjs-demo-db
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'nestjs_demo'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
      - '--default-authentication-plugin=mysql_native_password'
  mq:
    container_name: nestjs-demo-mq
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
